### PR TITLE
feat(autocomplete): add autocomplete

### PR DESCRIPTION
**Pull request by FlorianDevP**
I was interested what this preset does and so I looked at the source code. I saw that there was no autocomplete so I added it. Currently only tested in the playground. Might test it later on a project with Kobalte

### CODE REVIEW

**Comment by zirbest** [comment]
thank you @FlorianDevPhynix, it's possible to
- [ ] lint
- [ ] add some tests

**Comment by FlorianDevPhynix** [comment]
> thank you @FlorianDevPhynix, it's possible to
> 
> * [ ]  lint
> * [ ]  add some tests

Not sure what to test here. All of this is just for the editor.

The default preset also has no tests and lints for the autocomplete
https://github.com/unocss/unocss/tree/main/packages/preset-mini/src/_variants

**Comment by zirbest** [comment]
### autocomplete test example
https://github.com/unocss/unocss/blob/main/test/autocomplete-fuzzy.test.ts

### lint
```sh
npm run lint --fix
```

**Comment by FlorianDevPhynix** [comment]
Ok, I did lint fix and it added a single semicolon.
I definitely can write some tests based on this
> https://github.com/unocss/unocss/blob/main/test/autocomplete-fuzzy.test.ts

**Comment by FlorianDevPhynix** [comment]
I will have to added `@unocss/autocomplete` as a dev dependency.

Should I wrap all the different preset describe's in `autocomplete-fuzzy`?
```ts
describe('autocomplete-fuzzy', () => {
describe('unocss-preset-primitives', () => { ... })
...
})
```

**Comment by zirbest** [comment]
yep

**Comment by FlorianDevPhynix** [comment]
OK, the test are done.

**Comment by zirbest** [comment]
How about we try a more straightforward method?

```typescript
describe('unocss-preset-kobalte', async () => {
  const uno = createGenerator({
    rules: [['foo', { name: 'foo' }], ['bar', { name: 'bar' }]],
    presets: [presetKobalte()],
  })

  const ac = createAutocomplete(uno, {
    matchType: 'fuzzy',
  })

  it('check against impl', async () => {
    expect(await ac.suggest('uicl'))
      .include('ui-closed:')

    expect(await ac.suggest('uincl'))
      .include('ui-not-closed:')
  })
})

```

**Comment by zirbest** [comment]
thank you @FlorianDevPhynix
take a look at the new release

**Pull request closed without merging**
